name: 'backport conflict check'

on:
  pull_request_target:
    types: 
      - labeled
      - reopened

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  backportCheck:
    if: (github.event.action == 'labeled'
          && contains(github.event.label.name, 'backport'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout OpenSearch repo
        uses: actions/checkout@v4
        
      - name:  check conflicts
        run: |
          git remote add upstream https://github.com/opensearch-project/OpenSearch
          git fetch upstream main
          git checkout -b upstream_main --track upstream/main
          git config --global user.email "ci@example.com"
          git config --global user.name "ci"
          git merge --squash --allow-unrelated-histories ${{ github.event.pull_request.head.sha }}
          if [ $? -eq 0 ]; then
            git stash
            git fetch upstream 2.x
            git checkout -b upstream_2.x --track upstream/main
            result=$(git stash pop)
            if [[ $? -eq 0 ]]; then 
              echo 'No backport conflicts'; 
            else 
              conflicts=`echo $result | grep 'CONFLICT'`
              echo $conflicts
              # add comments to PR
            fi
          else:
            echo "conclict with main"
            exit;
          fi
          
